[package]
name = "peacock"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0", features = [ "from" ] }

peacock-pinion = { git = "https://github.com/nucleus-labs/pinion", rev = "f2a59d821ac7cec1e7a8d307f1a9ffc9514634a0" }
peacock-crest = {  git = "https://github.com/nucleus-labs/Crest",  rev = "1358d8bf06f4cb808b1d8d92fd4ee926bc89d41c" }
